test = {   'name': 'q1d',
    'points': 3,
    'suites': [   {   'cases': [   {'code': '>>> type(july_2019_mean) in (int, float, np.int64, np.float64)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> type(july_2020_mean) in (int, float, np.int64, np.float64)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(july_2019_mean, 75222.43333333333)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(july_2020_mean, 11177.619047619048)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
