test = {   'name': 'q3',
    'points': 0,
    'suites': [   {   'cases': [   {'code': '>>> callable(hailstone)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> hailstone(2) == 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> hailstone(3) == 10\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> (hailstone(10) == 5) and (hailstone(9) == 28)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
