test = {   'name': 'q2_4',
    'points': 0,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(seasons_sorted, Table)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': ">>> seasons_sorted.row(0).item('Year') == 1922\nTrue", 'hidden': False, 'locked': False},
                                   {'code': '>>> type(best_win_pct_year) in set([int, np.int32, np.int64])\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> best_win_pct_year == 1922\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
