test = {   'name': 'q4a',
    'points': 3,
    'suites': [   {   'cases': [   {'code': '>>> callable(one_streak)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> one_streak(make_array(13, 3, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 5, 7, 8)) == 9\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> one_streak(make_array(4, 1, 1, 1, 2, 3, 11, 1, 1, 1, 1, 1)) == 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> one_streak(make_array(5, 4, 1, 1, 1, 3, 2, 1, 2, 3)) == 3\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> one_streak(make_array(1, 2, 3, 4, 5)) == 1\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
