test = {   'name': 'q5b',
    'points': 2,
    'suites': [   {   'cases': [   {'code': ">>> all(fizz_buzz_sequence(8) == make_array('1', '2', 'fizz', '4', 'buzz', 'fizz', '7', '8'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> all(fizz_buzz_sequence(3) == make_array('1', '2', 'fizz'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> fizz_buzz_sequence(15).item(14) == 'fizz buzz'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': '>>> sum(fizz_buzz_sequence(1000) == "fizz") == 267\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
