test = {   'name': 'q4e',
    'points': 4,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(common_chains_pivoted, Table)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> common_chains_pivoted.num_rows == 6\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> common_chains_pivoted.labels == ('Segment_Category', 'rapid decrease', 'steady decrease', 'stagnant', 'steady increase', 'rapid increase')\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> all(common_chains_pivoted.column('stagnant') == make_array(187, 181.5, 162, 165.333333333333333333, 57, 172.5))\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> np.isclose(common_chains_pivoted.column("steady increase").item(2), 188.75)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
